{% set name = "neomodel" %}
{% set version = "6.0.0" %}
{% set sha256 = "658ccea86b66caa4165a59fe04b6c9cb905bf742a51c000d5f313d583657d695" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools
    - neo4j-python-driver >=4.3
    - pytz >=2021.1
    - neobolt >=1.7.17
    - six
    - shapely >=1.7.1

test:
  imports:
    - neomodel
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/robinedwards/neomodel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An object mapper for the neo4j graph database.

  description: |
    An Object Graph Mapper (OGM) for the neo4j graph database, built on the awesome neo4j_driver <https://github.com/neo4j/neo4j-python-driver>

    Familiar Django model style definitions.
    Powerful query API.
    Enforce your schema through cardinality restrictions.
    Full transaction support.
    Thread safe.
    pre/post save/delete hooks.
    Django integration via django_neomodel
  doc_url: http://neomodel.readthedocs.io/en/latest/
  dev_url: https://github.com/robinedwards/neomodel

extra:
  recipe-maintainers:
    - jan-janssen
    - pvanheus
