{% set name = "neomodel" %}
{% set version = "4.0.8" %}
{% set sha256 = "9049fa006149de741abc0c2b78725f07b90a6a630f3fb43df64efeb9a3a0071b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - neo4j-python-driver
    - pytz >=2017.2

test:
  imports:
    - neomodel
    - neomodel.cardinality
    - neomodel.config
    - neomodel.contrib
    - neomodel.contrib.semi_structured
    - neomodel.core
    - neomodel.exception
    - neomodel.hooks
    - neomodel.match
    - neomodel.properties
    - neomodel.relationship
    - neomodel.relationship_manager
    - neomodel.util
  commands:
    - neomodel_install_labels -h |grep Neo4j  # [not win]
    - neomodel_install_labels -h  # [win]


about:
  home: https://github.com/robinedwards/neomodel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An object mapper for the neo4j graph database.

  description: |
    An Object Graph Mapper (OGM) for the neo4j graph database, built on the awesome neo4j_driver <https://github.com/neo4j/neo4j-python-driver>

    Familiar Django model style definitions.
    Powerful query API.
    Enforce your schema through cardinality restrictions.
    Full transaction support.
    Thread safe.
    pre/post save/delete hooks.
    Django integration via django_neomodel
  doc_url: http://neomodel.readthedocs.io/en/latest/
  dev_url: https://github.com/robinedwards/neomodel

extra:
  recipe-maintainers:
    - pvanheus
