schema_version: 1

context:
  name: neomodel
  version: "6.1.0"
  sha256: 1c8c4e1c0e4e10ff58b214ee4822a0a6e2888318184ae648f8f5312ce0f2d547

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  file_name: ${{ name }}-${{ version }}.tar.gz

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - setuptools
    - neo4j-python-driver >=4.3
    - pytz >=2021.1
    - neobolt >=1.7.17
    - six
    - shapely >=1.7.1
    - typing_extensions

tests:
  - python:
      imports:
        - neomodel
      pip_check: false
      python_version: ${{ python_min }}
about:
  license: MIT
  license_file: LICENSE
  summary: An object mapper for the neo4j graph database.
  description: |
    An Object Graph Mapper (OGM) for the neo4j graph database, built on the awesome neo4j_driver <https://github.com/neo4j/neo4j-python-driver>

    Familiar Django model style definitions.
    Powerful query API.
    Enforce your schema through cardinality restrictions.
    Full transaction support.
    Thread safe.
    pre/post save/delete hooks.
    Django integration via django_neomodel
  homepage: https://github.com/robinedwards/neomodel
  repository: https://github.com/robinedwards/neomodel
  documentation: http://neomodel.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jan-janssen
    - pvanheus
