travis:
  secure:
    BINSTAR_TOKEN: XMga38w+gJAEr2jvIWRuVy+nqRgfGW02dLE/ZzXoL3irRKNIBK6KzYT7tYmQeDkmM5O9BcRpdxaj78MVyF0Gy8zbpCtmCySzfCpqypGeEWkwfa3yRrSNa5/WBVSxSB1FzAUK7ewrwHxYmYg1ByEssedrDN7GgklWvmZGnTN8K6yqnEiK4Vtm6RoCk53Jh/KrDIFfU4gDKarfZNXfUBPrTvrnrC2dXEQ/BNxRRFYmjjnklXrtoTuyyrML3Mk/M4XJYqFXtNqQcGpMXlYqVgiysqAcW38uMiusj50tTFyAZeUi3YRLaR83Yn+K8Locypuk5jFkMkzh4GJZtwDN23oHqeZPtL7Kew/VhJczKCue7W6tyNfzoQqbJQA8D/QFUBPbnu7CoP3HnQNxZ7poazAoqK744Vyi2uKRqmc5IPb5AtcNEt212hwdmYIpFTehbdwBzQgw7w5PTXSiXk+4uOJAtaHxH+K8+jSRabu47tWMpczW+29e4fvhDLOAPMGRsrwQJz2uluvG11cB20iG4RvzsDiGosZA6FDo9a8VPK7ZI5ZITmCySUwndwrBkDMeu5cAabdo8L0UiV767SORKWnl+ftQGKWPQhLw+nbMUaPTJD1j/iJ8jrDmKZQdOI7mCEr3IjH9b4hV9ikymqHsHDknD657ZgK1mJi2L/MSj25qKLM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
