travis:
  secure:
    BINSTAR_TOKEN: vZqVy+AE08d3nSDj9MI0G6nsXZMiwUBkf/Emdd5swWT5vRHGV816CsPwFc5nxjetGFG7oVr5WLsJY79g1GKiBR+EP9yNL2AmT7LeanhCb366xNCNZNq3ONn64KlKD10QqYYE5CMfXty4gFwzAEXRXjRnPZ1Jg1y5nSeyIUhSFYulcT2agCF7Dzi+TEF79FtyIJb3PqKoBTNawFZwJhBsHxppkZgG+MpLoMJfOdHEoOd2ymW2fsP8EtP0nrOUQlV6ClF+SGb79S0x1u0v2GfYh4NPhWz+mQ+bR/j9lfYw1+jBHIruD0iI0EuOJue+eWPRzzDjVa6yXP6mfFNmhXEcBm1PEbtMYRlxTkaRI2pbMhS3UXhUZYRx7IMluugASoT2Bnk+qI8WQNllR/sYUFWNTrPwqIVUgmqZJfe/iXmnIqzSoR5GPT1ohns7xv4J/8TCQsnhr9XJyUvYcSGWeL3M25BEwcPwFgdCKeK8PS5sldN58XLQdIKNeZaJKpifvnw2vZD5KjoeeW7N/7K95LRXWLbx/yvjAgcleeYazAesoY6XyKo+CM9lSiPqmCjrsc+MOIX7sZ6WtoWAlkvKA9k75vIz7CDJkpCKvp5CmFgYn6FernGu08NsPkJGZBDgFqNSbeVLVmOMkYi2SY1EhUxb2voJRrOyQsYJI1V24M4lf6k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
